package uk.co.rxmarkets.model.scoring;

public enum Category {

    INDUSTRY_SENTIMENT,
    POLITICAL_EXPOSURE,
    PRODUCTS_AND_SERVICES,
    CUSTOMER_SATISFACTION,
    GROWTH_POTENTIAL,
    CONFIDENCE_IN_BOARD,
    EMPLOYEE_SATISFACTION,
    OVERALL_SENTIMENT;

}
